### ISSUE TITLE
Widget not displaying stats

### ISSUE THREAD

**Issue by hugo-08** [Bunn/PiStatsMobile#1] opened 2020-09-17 03:56 UTC
hi,

just got the app installed and I see stats on the app but not on the widget. Any ideas?

![8351C558-8267-405A-AB04-EB1189068F54](https://user-images.githubusercontent.com/71421845/93418291-e7ee7480-f85e-11ea-902a-ac6f8f8a01c2.jpeg)
![584CF714-C73B-4CB5-98ED-A03388717F06](https://user-images.githubusercontent.com/71421845/93418294-ea50ce80-f85e-11ea-9c75-e8da655d799e.jpeg)

**Comment by bghvdhout** [comment] 2020-09-17 05:05
Exact same issue here
I do however get Widget info when I enter a IPv4 address instead of a hostname.
FYI: My DNS hostname has both AAAA & A record.
I'm not able to enter a static IPv6 address in the hostname field, e.g. [2000:123:123::1]

**Comment by Bunn** [comment] 2020-09-17 07:12
Try opening the app, it will force a refresh. I think there is an issue that the very first time the widget is on screen it doesn't fetch the data on a timely manner. 

If after opening the main app the widget still doesn't display the numbers, please let me know. Thanks.

**Comment by Bunn** [comment] 2020-09-17 07:14
Interesting. I'll investigate the issue when using a hostname. During tests I was using a remote server using ngrok and it worked fine but it seems I missed something

**Comment by lolfr** [comment] 2020-09-17 07:43
Same issue here. I’ve restarted my pu and my iPhone too.

**Comment by hugo-08** [comment] 2020-09-17 09:26
> Try opening the app, it will force a refresh. I think there is an issue that the very first time the widget is on screen it doesn't fetch the data on a timely manner.
> 
> If after opening the main app the widget still doesn't display the numbers, please let me know. Thanks.

still didn’t show stats after opening the app by tapping on the widget.

**Comment by Bunn** [comment] 2020-09-17 09:30
So, the app itself displays the information correctly, just not the widgets, right?
Are you using IPv4 on their setup or something different?

**Comment by lolfr** [comment] 2020-09-17 09:37
Yep. The app display correctly the info (even pi monitor) but not the widget. And I'm on IPv4.

**Comment by Bunn** [comment] 2020-09-17 09:43
@lolfr ok, this is interesting, I saw a bug like this when running a beta (4 I believe) but it was fixed later on, because if the app is displaying the information correctly but not the widget it's probably related to the way iOS tells the widget to fetch the new information.
I do have code that it's supposed to force a refresh once you open the host app, but if not even that is working seems to be more complicated than what I was thinking.

I'll take a look ASAP, try to reproduce on my side and see what can be improved.

I'm sorry your widget is not working out :( but hopefully I can find a fix soon.

**Comment by lolfr** [comment] 2020-09-17 09:50
It's ok. Widget is a new tech on iOS and a good to have. But the app is working well 👍

**Comment by Bunn** [comment] 2020-09-17 12:46
Found the issue, it seems I forgot to setup the App Transport Security Settings for the widget 😅
I'm going to send an update soon, hopefully it will fix the issue for everyone using a non-https domain.

Thanks for the report everyone, hopefully this will fix the issue. I'm sending version 1.1 to the App Store now.

**Comment by lolfr** [comment] 2020-09-17 15:35
Awesome 👏 

I’ve plan to switch my raspberry to https ASAP. Another reason to. 😄

Laurent

Envoyé de mon iPad

**Comment by kraetos10** [comment] 2020-09-17 16:17
I’m using non-https host (just my internal IP as I have a VPN) and i’m getting an error about it appearing offline - i suspect this is also due to the app transport stuff!  It’s a PITA - I’ve has issues with my apps too!

**Comment by hugo-08** [comment] 2020-09-18 01:17
> Found the issue, it seems I forgot to setup the App Transport Security Settings for the widget 😅
> 
> I'm going to send an update soon, hopefully it will fix the issue for everyone using a non-https domain.
> 
> 
> 
> Thanks for the report everyone, hopefully this will fix the issue. I'm sending version 1.1 to the App Store now.

just got the up date and it's working great! thanks Fernando.

**Comment by kraetos10** [comment] 2020-09-18 07:31
I have updated to new version but I still get an error. Mac version works, see attached screenshot for my setup: 

![IMG_2070](https://user-images.githubusercontent.com/1436236/93569306-41eb5900-f989-11ea-81c7-dcbb3284c637.png)
![IMG_2071](https://user-images.githubusercontent.com/1436236/93569313-457ee000-f989-11ea-9acc-a748b1d09dca.png)

**Comment by Bunn** [comment] 2020-09-18 07:46
@chriswunsch00 can you check under Settings.app->Pi Stats and see if you gave permissions to local network?
The fact that you said the mac version works makes me think it's related to permissions since both apps use the same connection library.

<img src="https://user-images.githubusercontent.com/782316/93570416-e4580c00-f98a-11ea-8066-8981df868866.png" width="400">

**Comment by kraetos10** [comment] 2020-09-18 07:57
@Bunn ah - I did not. Have enabled and all works! Thanks 👍

**Comment by Bunn** [comment] 2020-09-18 08:11
It seems that all issues were fixed, I'm closing this ticket then. Thanks everyone who reported the problem 👍

**Comment by lolfr** [comment] 2020-09-18 08:11
It’s working perfectly now !

Great job 👏 

Laurent

On the road.

**Closed as completed** 2020-09-18 08:11 UTC
